config/routes.rb
Rails.application.routes.draw do
  post '/invite', to: 'invites#create'
  get '/login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users, only: [:new, :create, :show]
  resources :events, only: [:new, :create, :show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :event_attendings
  has_many :attendees, through: :event_attendings, source: :user
  scope :past,   -> { where('date < ?', Time.now) }
  scope :upcoming, -> { where('date > ?', Time.now).order(date: :asc) }
end

app/models/event_attending.rb
class EventAttending < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events, class_name: "Event", foreign_key: :creator_id
  has_many :event_attendings
  has_many :attended_events, through: :event_attendings, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include ApplicationHelper
  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      redirect_to @event
    else
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
    @invite = EventAttending.new
  end

  def index
    @upcoming_events = Event.upcoming
    @past_events = Event.past
  end

  private

    def event_params
      params.require(:event).permit(:title, :date, :location, :description)
    end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  include ApplicationHelper
  before_action :correct_user

  def create
    user = User.find_by(name: invite_params[:name])
    @invite = user.event_attendings.build(event_id: @event.id)
    if @invite.save
      redirect_to @event
    else
      render @event
    end
  end

  private

    def invite_params
      params.permit(:event_id, :name)
    end

    def correct_user
      @event = Event.find(invite_params[:event_id])
      redirect_to @event unless current_user == @event.creator
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include ApplicationHelper
  def new
  end

  def create
    session[:user_id] = params[:user_id]
    redirect_to current_user
  end

  def destroy
    session.delete(:user_id)
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ApplicationHelper

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user.id)
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @created_events = @user.created_events
    @upcoming_events = @user.attended_events.upcoming
    @prev_events = @user.attended_events.past
  end

  private

    def user_params
      params.require(:user).permit(:name,:email,:password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include SessionsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def sign_in(user_id)
    session[:user_id] = user_id
  end

  def current_user
    User.find_by_id(session[:user_id])
  end

  def signed_in?
    !current_user.nil?
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<li style="list-style-type: none">
  <h2><%= link_to event.title, event %></h2>
  <h4>
    Hosted by <%= event.creator.name %>
    Location: <%= event.location %>
    Date: <%= event.date %>
  </h4>
  <p> <%= event.description %> </p>
  <h3>Attendees:</h3>
  <ol>
    <% event.attendees.each do |attendee| %>
      <li> <%= attendee.name %> </li>
    <% end %>
  </ol>
</li>

app/views/events/_invite_form.html.erb
<%= form_tag(invite_path, method: :post) do %>
  <%= hidden_field_tag :event_id, @event.id %>

  <%= label_tag :name, "Invite User:" %>
  <%= text_field_tag :name %>

  <%= submit_tag 'Invite User' %>
<% end %>

app/views/events/index.html.erb
<h1>Event Index</h1>
<%= link_to "Create new event", new_event_path %>
<h2>Upcoming Events:</h2>
<ol><%= render @upcoming_events %></ol>
<h2>Past Events: </h2>
<ol><%= render @past_events %></ol>

app/views/events/new.html.erb
<h1> Create new Event </h1>

<%= form_for(@event) do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :location %>
  <%= f.text_field :location %>

  <%= f.label :date %>
  <%= f.date_field :date %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.submit "Create event" %>

<% end %>

app/views/events/show.html.erb
<%= render @event %>
<%= render 'invite_form' if current_user == @event.creator %>

app/views/invites/create.html.erb
<h1>Invites#create</h1>
<p>Find me in app/views/invites/create.html.erb</p>

app/views/invites/new.html.erb
<h1>Invites#new</h1>
<p>Find me in app/views/invites/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul id="heading">
    <% if signed_in? %>
      <li class="heading-item">
        <%= link_to current_user.name, current_user, class:"heading-link" %>
      </li>
      <li class="heading-item">
        <%= link_to "Logout", logout_path, method: :delete, class: "heading-link" %>
      </li>
    <% else %>
      <li class="heading-item">
        <%= link_to "Sign Up", new_user_path, class: "heading-link" %>
      </li>
      <li class="heading-item">
        <%= link_to "Login", login_path, class: "heading-link"%>
      </li>
    <% end %>
      <li class="heading-item">
        <%= link_to "All Events", events_path, class: "heading-link" %>
      </li>
    </ul>
    <%= yield %>
  </body>
</html>

app/views/users/_user_form.html.erb
<%= form_for(@user) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit "Create New User" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up<h1>

<%= render 'user_form' %>

app/views/users/show.html.erb
<h1><%= @user.name %>'s Profile</h1>
<h3>Email Address: <%= @user.email %></h3>
<% if @created_events.any? %>
  <h2>Created Events:</h2>
  <ol>
    <%= render @created_events %>
  </ol>
<% end %>

<% if @upcoming_events.any? %>
  <h2>Created Events:</h2>
  <ol>
    <%= render @user.created_events %>
  </ol>
<% end %>

<% if @prev_events.any? %>
  <h2>Created Events:</h2>
  <ol>
    <%= render @user.created_events %>
  </ol>
<% end %>